export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS";

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_TOTAL = 'GET_CART_TOTAL';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const SINGLE_PRODUCT='SINGLE_PRODUCT'
